//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Resources;

namespace UltrakULL {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Resources.ResourceManager templates;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        
        static Resources()
        {
            var assembly = typeof(Resources).Assembly;
            resourceMan = new global::System.Resources.ResourceManager("UltrakULL.Resources.Resources", assembly);
            templates = new global::System.Resources.ResourceManager("UltrakULL.Resources.TemplateResources", assembly);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] SubtitledSources {
            get {
                object obj = resourceMan.GetObject("SubtitledSources", resourceCulture);
                return ((byte[])(obj));
            }
        }        
        
        internal static string MirageDialogObjects {
            get {
                object obj = resourceMan.GetObject("MirageDialogObjects", resourceCulture);
                return ((string)(obj));
            }
        }        
        
        internal static string MuseumBooks {
            get {
                object obj = resourceMan.GetObject("MuseumBooks", resourceCulture);
                return ((string)(obj));
            }
        }
        
        internal static string Intro {
            get {
                object obj = templates.GetObject("Intro", resourceCulture);
                return ((string)(obj));
            }
        }

        internal static string Bios {
            get {
                object obj = templates.GetObject("Bios", resourceCulture);
                return ((string)(obj));
            }
        }
        
        internal static string Strategies {
            get {
                object obj = templates.GetObject("Strategies", resourceCulture);
                return ((string)(obj));
            }
        }
        
        internal static string Books {
            get {
                object obj = templates.GetObject("Books", resourceCulture);
                return ((string)(obj));
            }
        }
        
        internal static string DevMuseum {
            get {
                object obj = templates.GetObject("DevMuseum", resourceCulture);
                return ((string)(obj));
            }
        }
        
        internal static string PrimeSanctums {
            get {
                object obj = templates.GetObject("PrimeSanctums", resourceCulture);
                return ((string)(obj));
            }
        }
        
        internal static string Testaments {
            get {
                object obj = templates.GetObject("Testaments", resourceCulture);
                return ((string)(obj));
            }
        }
        
        internal static string Intermissions {
            get {
                object obj = templates.GetObject("Intermissions", resourceCulture);
                return ((string)(obj));
            }
        }
        
        internal static string Mirage {
            get {
                object obj = templates.GetObject("Mirage", resourceCulture);
                return ((string)(obj));
            }
        }
    }
}
